Repository conda/constructor, pull requests merged in 2023-07, with the labels that each got.

#692 Fix transmutation with micromamba
  constructor/preconda.py
  news/692-micromamba-transmutation
Labels: cla-signed

#694 Update name of org-wide canary channel token.
  .github/workflows/main.yml
Labels: cla-signed

#697 Prepare 3.4.4
  .authors.yml
  .mailmap
  AUTHORS.md
  CHANGELOG.md
  news/652-fix-edit-doc-link
  news/654-fix_channel_remap
  news/659-write-repodata
  news/660-ruamel-yaml
  news/663-document-cli
  news/664-fix-yes-no-parsing
  news/665-install-spaces-silent
  news/669-mkdir-home
  news/675-pytest-examples
  news/676-new-repodata-interface
  news/678-default-home-not-set
  news/684-uninstaller-check-registry
  news/692-micromamba-transmutation
  news/696-uninstaller-fixes
Labels: cla-signed

#699 Prohibit parentheses in INSTDIR
  constructor/nsis/main.nsi.tmpl
  news/699-prohibit-parentheses-instdir
Labels: cla-signed

#698 add light docs about uninstallation procedures
  docs/source/cli-options.md
  docs/source/howto.md
  news/698-uninstall-docs
Labels: cla-signed, documentation::how-tos

#702 Skip test_write_images on Linux
  news/702-skip-imaging-test-linux
  tests/test_imaging.py
Labels: cla-signed

#703 Update requirements
  news/703-adjust-reqs
  recipe/meta.yaml
  setup.py
Labels: cla-signed

#477 Fix environment and environment_file modes
  CONSTRUCT.md
  constructor/conda_interface.py
  constructor/construct.py
  constructor/fcp.py
  docs/source/construct-yaml.md
  examples/from_env_txt/construct.yaml
  examples/from_env_txt/env.txt
  examples/from_env_yaml/construct.yaml
  examples/from_env_yaml/env.yaml
  examples/from_existing_env/construct.yaml
  examples/from_explicit/construct.yaml
  examples/from_explicit/explicit_linux-64.txt
  examples/from_explicit/explicit_osx-arm64.txt
  news/477-from-environment-fixes
  scripts/run_examples.py
  tests/test_examples.py
Labels: type::bug, cla-signed
